from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from vendorverdict.storage import ReportStore
from vendorverdict.tools.evidence import EvidenceCollector
from vendorverdict.verdict import build_vendor_verdict, render_verdict


@dataclass(frozen=True)
class BuiltReport:
    report_id: str | None
    report_text: str


def build_report(raw_query: str, use_live_evidence: bool | None = None) -> tuple[object, str]:
    """Build a VendorVerdict once and return both structured verdict and text."""
    collector = EvidenceCollector(use_live_checks=use_live_evidence)
    verdict = build_vendor_verdict(raw_query, collector=collector)
    return verdict, render_verdict(verdict)


def build_and_optionally_save_report(
    raw_query: str,
    *,
    use_live_evidence: bool | None = None,
    save_report: bool = False,
    db_path: str | Path | None = None,
) -> BuiltReport:
    verdict, report_text = build_report(raw_query, use_live_evidence=use_live_evidence)
    report_id: str | None = None
    if save_report and not verdict.request.missing_fields and verdict.recommendation is not None:
        store = ReportStore(db_path)
        report_id = store.save_report(verdict, report_text, raw_query=raw_query)
    return BuiltReport(report_id=report_id, report_text=report_text)


def render_report_markdown(report: dict[str, Any]) -> str:
    vendors = ", ".join(report.get("vendors", []))
    lines = [
        f"# VendorVerdict Report: {vendors}",
        "",
        f"- Report ID: `{report['id']}`",
        f"- Created: {report['created_at']}",
        f"- Type: {report['report_type']}",
        f"- Use case: {report['use_case']}",
        f"- Recommendation: {report.get('recommendation') or 'N/A'}",
        f"- Confidence: {report['confidence']}",
        "",
        "## Full report",
        "",
        report["rendered_response"],
        "",
        "## Scorecard",
        "",
        "| Vendor | Overall | Security | Privacy | Pricing | Lock-in | SME fit | Confidence |",
        "|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for score in report.get("scores", []):
        lines.append(
            f"| {score['vendor']} | {score['overall']} | {score['security']} | {score['privacy']} | "
            f"{score['pricing_predictability']} | {score['lock_in']} | {score['sme_fit']} | {score['confidence']} |"
        )

    lines.extend(["", "## Evidence snapshot", ""])
    evidence_items = report.get("evidence_items", [])
    if evidence_items:
        lines.append("| Vendor | Source | Type | Reachable | Status | URL | Note |")
        lines.append("|---|---|---|---|---:|---|---|")
        for item in evidence_items:
            if item.get("ok") is None:
                reachable = "fallback"
            else:
                reachable = "yes" if item.get("ok") else "no"
            status = item.get("status_code") or ""
            url = item.get("url") or ""
            if item.get("final_url"):
                url = f"{url} → {item['final_url']}"
            lines.append(
                f"| {item.get('vendor', '')} | {item.get('label', '')} | {item.get('source_type', '')} | "
                f"{reachable} | {status} | {url} | {item.get('note', '')} |"
            )
    else:
        lines.append("No structured evidence rows were stored for this report.")

    lines.extend(["", "## Extracted evidence findings", ""])
    findings = report.get("evidence_findings", [])
    if findings:
        lines.append("| Vendor | Finding | Source | Confidence | Snippet |")
        lines.append("|---|---|---|---|---|")
        for finding in findings:
            snippet = str(finding.get("snippet", "")).replace("|", "\\|")
            source = f"{finding.get('source_label', '')}: {finding.get('source_url', '')}"
            lines.append(
                f"| {finding.get('vendor', '')} | {finding.get('label', '')} | {source} | "
                f"{finding.get('confidence', '')} | {snippet} |"
            )
    else:
        lines.append("No extracted evidence findings were stored for this report.")

    lines.extend(["", "---", "", "Generated by VendorVerdict. Procurement guidance only; not legal advice or a formal security audit."])
    return "\n".join(lines)


def export_report_markdown(report_id: str, output_dir: str | Path = "reports", store: ReportStore | None = None) -> Path:
    report_store = store or ReportStore()
    report = report_store.get_report(report_id)
    if report is None:
        raise KeyError(f"Report not found: {report_id}")
    output_path = Path(output_dir) / f"vendorverdict-report-{report_id}.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_report_markdown(report), encoding="utf-8")
    return output_path
