from __future__ import annotations

from vendorverdict.payment.pricing import PREMIUM_VENDOR_DOSSIER
from vendorverdict.verdict import build_vendor_verdict, render_response
from vendorverdict.tools.evidence import EvidenceCollector


def wants_premium_report(text: str) -> bool:
    """Detect requests to upgrade a free review into a paid premium report."""

    lowered = text.lower()
    return any(
        phrase in lowered
        for phrase in (
            "premium",
            "upgrade",
            "vendor dossier",
            "paid report",
            "full procurement report",
            "board-ready",
            "board ready",
            "procurement dossier",
            "risk register",
            "approval conditions",
        )
    )


def render_upgrade_cta() -> str:
    return (
        f"Premium option: say 'Upgrade to Premium Vendor Dossier' to request the paid "
        f"{PREMIUM_VENDOR_DOSSIER.name} for {PREMIUM_VENDOR_DOSSIER.price_fet} FET. "
        "It adds a procurement memo, risk register, approval conditions, rollout checklist, "
        "and expanded vendor questions."
    )


def render_payment_offer(reference: str | None = None) -> str:
    ref_text = f"\nPayment reference: {reference}" if reference else ""
    return (
        f"💳 {PREMIUM_VENDOR_DOSSIER.name} costs {PREMIUM_VENDOR_DOSSIER.price_fet} FET.\n\n"
        "I am sending a Fetch.ai Payment Protocol request now. After payment is committed "
        "and verified, I will generate the premium report directly in this ASI:One chat.\n\n"
        "Premium report includes:\n"
        "- executive procurement memo,\n"
        "- approval conditions,\n"
        "- vendor risk register,\n"
        "- rollout checklist,\n"
        "- expanded due-diligence questionnaire,\n"
        "- evidence appendix."
        f"{ref_text}"
    )


def render_premium_dossier(raw_query: str, use_live_evidence: bool | None = True) -> str:
    """Generate a premium procurement dossier after payment has been accepted.

    The report reuses the same multi-agent evidence/scoring pipeline, then adds a
    decision memo and rollout artifacts. This keeps the paid product credible while
    avoiding a second fragile workflow.
    """

    collector = EvidenceCollector(use_live_checks=use_live_evidence)
    verdict = build_vendor_verdict(raw_query, collector=collector)
    base_report = render_response(raw_query, use_live_evidence=use_live_evidence)

    if verdict.request.missing_fields or not verdict.recommendation:
        return base_report

    winner = verdict.recommendation
    request = verdict.request
    compared_vendors = ", ".join(request.vendors)

    approval_conditions = [
        "Confirm data hosting/processing locations and GDPR/DPA terms before rollout.",
        "Confirm SSO, MFA, RBAC, and audit-log availability on the intended plan.",
        "Confirm whether customer data is used for AI model training or product analytics beyond service delivery.",
        "Confirm data retention, deletion, export, and account-closure terms.",
        "Pilot with a limited workspace and non-critical data before full adoption.",
    ]

    risk_register = [
        ("Security controls", "Medium", "Verify SSO/MFA/RBAC/audit logs on the selected plan."),
        ("Privacy/compliance", "Medium", "Request DPA/GDPR/subprocessor details from the vendor."),
        ("Pricing expansion", "Medium", "Model expected seat and feature growth over 12 months."),
        ("Workflow lock-in", "Medium", "Test export/import before storing critical client records."),
        ("Operational rollout", "Low-Medium", "Start with a controlled pilot and admin ownership."),
    ]

    lines: list[str] = []
    lines.append("💎 Premium Vendor Dossier")
    lines.append("")
    lines.append("Payment-gated report generated by VendorVerdict after Payment Protocol confirmation.")
    lines.append("")
    lines.append("Executive procurement memo:")
    lines.append(
        f"For {request.use_case}, VendorVerdict reviewed {compared_vendors}. "
        f"The recommended practical choice is {winner.vendor}, with an overall score of {winner.overall}/100. "
        "This recommendation is conditional on the vendor confirming the security, privacy, export, "
        "and pricing questions listed below."
    )
    lines.append("")
    lines.append("Approval conditions:")
    for idx, condition in enumerate(approval_conditions, start=1):
        lines.append(f"{idx}. {condition}")
    lines.append("")
    lines.append("Vendor risk register:")
    lines.append("| Risk area | Severity | Mitigation |")
    lines.append("|---|---|---|")
    for area, severity, mitigation in risk_register:
        lines.append(f"| {area} | {severity} | {mitigation} |")
    lines.append("")
    lines.append("Rollout checklist:")
    rollout_steps = [
        "Run a two-week pilot with one project/team.",
        "Assign an internal admin and backup admin.",
        "Enable MFA and least-privilege access before importing client data.",
        "Document export steps and test one sample export.",
        "Review vendor answers before full rollout.",
    ]
    for step in rollout_steps:
        lines.append(f"- {step}")
    lines.append("")
    lines.append("Expanded due-diligence questions:")
    expanded_questions = [
        "Can you provide your latest SOC 2 or equivalent security report summary?",
        "Can you share your DPA, subprocessor list, and data transfer terms?",
        "Which security controls are included in the plan suitable for our team size?",
        "What happens to customer data after account cancellation?",
        "What are the exact export formats and API access limits?",
        "What pricing or feature thresholds should we expect as usage grows?",
        "How do you notify customers about security incidents or material policy changes?",
    ]
    for idx, question in enumerate(expanded_questions, start=1):
        lines.append(f"{idx}. {question}")
    lines.append("")
    lines.append("Evidence appendix:")
    for score in verdict.scores:
        source_count = len(score.source_checks) or len(score.evidence_urls)
        confidence = score.confidence
        lines.append(f"- {score.vendor}: {source_count} configured source target(s), confidence {confidence}.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(base_report)
    return "\n".join(lines)
